name: hello -world
'on': push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-steps
        run: echo "Hello world" 
      - name: new step
        run: echo " hello from other world"
  
